FROM node:20-alpine3.18 AS base
ENV YARN_VERSION=4.0.1
RUN corepack enable && corepack prepare yarn@${YARN_VERSION}
RUN yarn global add turbo
WORKDIR /www
COPY . .
COPY ../.env-dev ../apps/web/.env.production
RUN yarn
RUN turbo build


FROM base AS builder
WORKDIR /www
COPY --from=base /www/apps/web .

EXPOSE 3000
CMD [ "yarn", "run", "preview"]
