FROM node:20-alpine3.18 AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS builder
WORKDIR /www
COPY ../ .
RUN pnpm install
RUN pnpm deploy --filter=web /www/web

FROM builder AS web
WORKDIR /www/web
COPY --from=builder /www/web .
COPY ../.env-dev .env.production
RUN npm run build
EXPOSE 8080
CMD ["npm", "run", "preview"]


