FROM node:20-alpine3.18 AS base
ENV YARN_VERSION=4.0.1
RUN corepack enable && corepack prepare yarn@${YARN_VERSION}
RUN yarn global add turbo
WORKDIR /www
COPY . .
RUN yarn
RUN turbo build


FROM base AS builder
WORKDIR /www
COPY --from=base /www/apps/api .
COPY ../.env-dev .env
EXPOSE 3000
CMD [ "yarn", "run", "start:prod"]
