
# FROM node:20-alpine3.18 AS base
# ENV PNPM_HOME="/pnpm"
# ENV PATH="$PNPM_HOME:$PATH"
# RUN corepack enable

# FROM base AS builder
# WORKDIR /www
# COPY ../ .
# RUN pnpm install

# # RUN pnpm run -r build
# RUN pnpm deploy --filter=api /www/api

# FROM node:20-alpine3.18 AS api
# WORKDIR /www/api
# COPY --from=builder /www/api .
# COPY ../.env-dev .env
# RUN npm run build
# EXPOSE 3001
# CMD [ "npm", "run", "start:prod"]




FROM node:20-alpine3.18 AS base
ENV YARN_VERSION=4.0.1
RUN corepack enable && corepack prepare yarn@${YARN_VERSION}
RUN yarn global add turbo
WORKDIR /www
COPY . .
# COPY ../.env-dev apps/web/.env.production
RUN yarn
RUN turbo build


FROM base AS builder
WORKDIR /www
COPY --from=base /www/apps/api .
COPY ../.env-dev .env
EXPOSE 3000
CMD [ "yarn", "run", "start:prod"]
